// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback to hardcoded values if env vars are missing (Force fix)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ragnzmmnqtogmodkfayj.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZ256bW1ucXRvZ21vZGtmYXlqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQwMDYzNSwiZXhwIjoyMDgzOTc2NjM1fQ.QygPn4fvslB0HEHvVHNGry0L3lRTrQnvFCloqaUzQfk";
console.log('Supabase Client Initialized with:', { SUPABASE_URL });

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});